Use Kontena::Command hooks and new authentication mechanism.
kontena/kontena-plugin-azure pull request #4
Opened 2016-08-17 13:27 UTC by kke

2016-10-10 05:47 UTC, jakolehm requested changes

2016-10-10 05:47 UTC, jakolehm commented on lib/kontena/machine/azure/cloudinit_master.yml
> +            <% if server_name %>-e KONTENA_SERVER_NAME=<%= server_name %><% end %> \
`KONTENA_SERVER_NAME` => `SERVER_NAME`

2016-10-10 05:47 UTC, jakolehm commented on lib/kontena/machine/azure/cloudinit_master.yml
> +            <% if initial_admin_code %>-e KONTENA_INITIAL_ADMIN_CODE=<%= intial_admin_code %><% end %> \
`KONTENA_INITIAL_ADMIN_CODE`=> `INITIAL_ADMIN_CODE`

2016-10-24 12:49 UTC, jakolehm approved these changes

2016-10-24 12:50 UTC, jakolehm commented on lib/kontena/machine/azure/cloudinit.yml
> +		- name: etcd2.service
something is wrong here?

2016-10-25 06:50 UTC, kke commented on lib/kontena/machine/azure/cloudinit.yml
> +		- name: etcd2.service
Perhaps tabs instead of spaces.

2016-10-25 07:35 UTC, jakolehm approved these changes

2016-10-25 07:35 UTC, merged